/* (c) https://github.com/MontiCore/monticore */

package cdfeaturediagram;

import featurediagram._symboltable.FeatureDiagramScope;
import featurediagram._symboltable.FeatureDiagramScopeBuilder;

public class CDTypeFeatureDiagramScopeBuilder extends FeatureDiagramScopeBuilder {

  @Override
  public FeatureDiagramScope build ()  {
    /* generated by template _symboltable.scope.BuildScope*/

    FeatureDiagramScope scope = new CDTypeFeatureDiagramScope(shadowing);
    this.spanningSymbol.ifPresent(scope::setSpanningSymbol);
    scope.setExportingSymbols(this.exportingSymbols);
    scope.setEnclosingScope(this.enclosingScope);
    scope.setSubScopes(this.subScopes);
    if (this.isPresentAstNode()) {
      scope.setAstNode(this.getAstNode());
    } else {
      scope.setAstNodeAbsent();
    }
    this.name.ifPresent(scope::setName);
    this.subScopes.forEach(s -> s.setEnclosingScope(scope));
    return scope;
  }
}
