# (c) https://github.com/MontiCore/monticore  
image: maven:3.5.4-jdk-8-alpine

cache:
  paths:
    - .m2/

stages:
  - build-sources
  - it-test

build_sources:
  stage: build-sources
  script:
    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install
    
trigger_langexp:                        
  stage: it-test                           
  trigger:                              
    project: monticore/langexperiments  
    branch: dev                         
  only:
    - develop
