# (c) https://github.com/MontiCore/monticore  
image: maven:3.5.4-jdk-8-alpine

cache:
  paths:
    - .m2/

stages:
  - build-sources
#  - it-test

build_gradle:
  stage: build-sources
  script:
    - chmod +x gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - "./gradlew build"
  artifacts:
    paths:
      - "fd-analysis/target/lib/FACT.jar"
      - "fd-lang/target/lib/FeatureDiagramTool.jar"
      - "fd-lang/target/lib/FeatureConfigurationTool.jar"
      - "fd-lang/target/lib/FeatureConfigurationPartialTool.jar"
    expire_in: 1 week


# trigger_langexp:                        
#  stage: it-test                           
#  trigger:                              
#    project: monticore/langexperiments  
#    branch: dev                         
#  only:
#    - develop
