/* (c) https://github.com/MontiCore/monticore */

import com.github.sherter.googlejavaformatgradleplugin.VerifyGoogleJavaFormat
plugins {
    id 'java'
    id 'java-gradle-plugin'
    id 'jacoco'
    id 'de.monticore.generator' version "$mc_version"
    id 'com.gradleup.shadow' version "$shadow_plugin_version"
    id 'maven-publish'
    id "com.github.sherter.google-java-format" version "0.9"  // Task "verifyGoogleJavaFormat" and "googleJavaFormat"

}

project(':fd-conformance') {

    dependencies {
        implementation group: 'org.slf4j', name: 'slf4j-simple', version: slf4j_version
        implementation group: 'de.se_rwth.commons', name: 'se-commons-logging', version: logging_version
        implementation group: 'de.monticore', name: 'monticore-runtime', version: mc_version
        implementation group: 'de.monticore', name: 'monticore-grammar', version: mc_version
        implementation group: 'de.monticore', name: 'class2mc', version: mc_version
        implementation project(':fd-lang')
        implementation group: 'com.google.guava', name: 'guava', version: guava_version
        implementation group: 'de.monticore.lang.ocl', name: 'ocl2smt', version: mc_version
        implementation 'org.junit.jupiter:junit-jupiter:5.7.0'
        implementation 'edu.mit.alloy:alloy:6'
        implementation 'tools.aqua:z3-turnkey:4.11.2'
        implementation "de.monticore.lang:cd4analysis:$mc_version:cd2smt" //todo remover later ?

        testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
        testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
        testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
        testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"

        implementation "de.se_rwth.commons:se-commons-groovy:$mc_version"
        grammar("de.monticore:monticore-grammar:$mc_version")
    }

    test {
        useJUnitPlatform()
    }

    compileJava {
        dependsOn project.collect { it.tasks.withType(MCTask) }
    }

    group = 'fd-conformance'
    repositories {
        if (("true").equals(getProperty('useLocalRepo'))) {
            mavenLocal()
        }
        maven {
            credentials.username mavenUser
            credentials.password mavenPassword
            url repo
        }
        mavenCentral()
    }

    description = 'SLE-Project: Conformance Checking for Feature Diagrams'
    buildDir = file("$projectDir/target")

    googleJavaFormat {
        exclude '**/target/**'
    }

    verifyGoogleJavaFormat {
        ignoreFailures true
        exclude "**"
    }  // do not check format in "build"

    tasks.register('checkfmt', VerifyGoogleJavaFormat) {}

    tasks.register('fmt') {
        dependsOn tasks.named("googleJavaFormat")
    }

    jar.dependsOn(shadowJar)
    shadowJar {
        zip64(true)
        manifest {
            attributes "Main-Class": "de.monticore.fd.conformance.FDConformanceTool"
        }

        archiveFileName = "MCFDC.jar"
        destinationDirectory = file('target/libs')
        archiveClassifier = "tool"

    }
}
