# (c) https://github.com/MontiCore/monticore
name: Test Proposed Changes

concurrency: # run this test workflow only once per "branch"
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: # run this pipeline on every push
    paths-ignore:
      - "*.md" # do not run this pipeline if the only change was to markdown files
    branches-ignore: [ "dev" ] # Do not run this on the default branch

env:
  GRADLE_VERSION: 8.5 # Gradle version used
  GRADLE_CLI_OPTS: "-Pci --build-cache --refresh-dependencies" # CLI options passed to Gradle
  GRADLE_BUILD_ACTION_CACHE_KEY_JOB: "test-cache-${{ github.head_ref }}.${{ github.sha }}"

permissions:
  contents: read 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{env.GRADLE_VERSION}}
      - name: Gradle build
        run: gradle build ${{env.GRADLE_CLI_OPTS}}
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: junit-test-results
          path: '**/target/test-results/test/TEST-*.xml'
          retention-days: 1
